jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        dependency-graph: generate-and-submit
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew --no-daemon build
    - continue-on-error: true
      name: Compress archive
      run: gzip -n -9 build/distributions/signal-cli-*.tar
    - continue-on-error: true
      name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: signal-cli-archive-${{ matrix.java }}
        path: build/distributions/signal-cli-*.tar.gz
    strategy:
      matrix:
        java:
        - '21'
  build-graalvm:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: graalvm/setup-graalvm@v1
      with:
        cache: gradle
        github-token: ${{ secrets.GITHUB_TOKEN }}
        java-version: '21'
        version: latest
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew --no-daemon nativeCompile
    - continue-on-error: true
      name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: signal-cli-native
        path: build/native/nativeCompile/signal-cli
name: signal-cli CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
permissions:
  contents: write
